apiVersion: v1
kind: Service
metadata:
  name: kamf-api-service
  labels:
    app: kamf-api
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: kamf-api