apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamf-web
spec:
  replicas: 2  # High availability
  template:
    spec:
      containers:
      - name: web
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://kamf.site/api"
        - name: NEXTAUTH_URL
          value: "https://kamf.site"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"