# Nginx Ingress for development environment
# Replaces Traefik IngressRoute with standard Kubernetes Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kamf-dev-ingress
  labels:
    app: kamf
    environment: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # cert-manager.io/cluster-issuer: letsencrypt-prod  # Disabled for now
    nginx.ingress.kubernetes.io/server-snippets: |
      location /api {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://upstream_balancer;
      }
spec:
  # tls:  # Disabled for initial testing
  #   - hosts:
  #       - dev.kamf.site
  #     secretName: kamf-dev-tls
  rules:
    - host: dev.kamf.site
      http:
        paths:
          # API routes - handle /api prefix stripping
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kamf-api-service
                port:
                  number: 8000
          # Web routes - catch all other paths
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kamf-web-service
                port:
                  number: 3000
