apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/api
- ../../base/web
- ../../base/mysql
- namespace.yaml
- nodeport-services.yaml
- ingress-route.yaml
- secrets.yaml


images:
- name: chansparcs/kamf-api
  newName: chansparcs/kamf-api
  newTag: dev
- name: chansparcs/kamf-web
  newName: chansparcs/kamf-web
  newTag: dev
namespace: kamf-dev
patches:
- path: api-patch.yaml
- path: web-patch.yaml
- path: mysql-patch.yaml
